# Package and data-contract pages from active use-case frontmatter.

using TOML

"""
Harness relationship for a catalogue integration surface.

- `:harness` — Julia package listed in root `Project.toml` deps
- `:candidate` — referenced by use cases but not (yet) a harness dep
- `:data` — non-Julia data contract (`role: data`)
"""
@enum PackageHarnessStatus harness candidate data

struct PackageSurface
    name::String
    roles::Set{String}
    cases::Vector{UseCaseRecord}
    status::PackageHarnessStatus
    page_path::Union{String, Nothing}  # path relative to docs/src/
end

function harness_julia_deps()
    isfile(HARNESS_PROJECT_PATH) || return Set{String}()
    proj = TOML.parsefile(HARNESS_PROJECT_PATH)
    deps = get(proj, "deps", Dict())
    deps isa AbstractDict || return Set{String}()
    return Set{String}(string(k) for k in keys(deps))
end

function is_active_usecase(record::UseCaseRecord)
    return get(record.meta, "status", nothing) == "active"
end

function collect_package_mentions(records::Vector{UseCaseRecord})
    pkg_cases = Dict{String, Vector{UseCaseRecord}}()
    pkg_roles = Dict{String, Set{String}}()
    for record in records
        is_active_usecase(record) || continue
        pkgs = get(record.meta, "packages", nothing)
        pkgs isa AbstractVector || continue
        for item in pkgs
            item isa AbstractDict || continue
            name = string(get(item, "name", ""))
            name == "" && continue
            role = string(get(item, "role", ""))
            push!(get!(pkg_cases, name, UseCaseRecord[]), record)
            roles = get!(pkg_roles, name, Set{String}())
            role != "" && push!(roles, role)
        end
    end
    return pkg_cases, pkg_roles
end

function classify_package(name::AbstractString, roles::Set{String}, harness_deps::Set{String})
    "data" in roles && return data
    string(name) in harness_deps && return harness
    return candidate
end

function package_kind(status::PackageHarnessStatus)
    status === data && return "data"
    return "julia"
end

function package_status_key(status::PackageHarnessStatus)
    status === harness && return "harness"
    status === candidate && return "candidate"
    return "data"
end

function usecase_refs_for(surface::PackageSurface)
    refs = String[]
    for record in surface.cases
        id = string(get(record.meta, "id", record.page_ref))
        version = usecase_version_int(record.meta)
        if version === nothing
            push!(refs, id)
        else
            push!(refs, usecase_ref(id, version))
        end
    end
    return sort(unique(refs))
end

function write_packages_toml!(src_dir::AbstractString, surfaces::Vector{PackageSurface})
    path = joinpath(src_dir, GENERATED_PACKAGES_TOML)
    open(path, "w") do io
        println(io, "# Generated from active usecases/*/usecase.md — do not edit by hand.")
        println(io, "# Regenerated by docs/make.jl at Documenter build time.")
        println(io)
        for surface in sort(surfaces; by=s -> s.name)
            isempty(surface.cases) && continue
            println(io, "[$(surface.name)]")
            println(io, "kind = \"$(package_kind(surface.status))\"")
            println(io, "harness_status = \"$(package_status_key(surface.status))\"")
            roles = sort(collect(surface.roles))
            if isempty(roles)
                println(io, "roles = []")
            else
                println(io, "roles = [$(join(["\"$r\"" for r in roles], ", "))]")
            end
            refs = usecase_refs_for(surface)
            println(io, "usecases = [$(join(["\"$r\"" for r in refs], ", "))]")
            println(io)
        end
    end
    return path
end

function package_doc_href(name::AbstractString, page_path::Union{String, Nothing}; from_generated::Bool=true)
    page_path === nothing && return "``$name``"
    from_generated && return "[$name]($(basename(page_path)))"
    return "[$name]($page_path)"
end

function status_label(status::PackageHarnessStatus)
    status === harness && return "In harness"
    status === candidate && return "Candidate (external)"
    return "Data contract"
end

function package_edit_url(surface::PackageSurface)
    isempty(surface.cases) && return nothing
    record = surface.cases[1]
    return "$REPO_EDIT_BASE/usecases/$(record.dir_name)/usecase.md"
end

function render_package_page(surface::PackageSurface)
    name = surface.name
    roles = join(sort(collect(surface.roles)), ", ")
    cases = ["[$(r.page_ref)](../usecases/$(r.page_ref).md)" for r in surface.cases]
    edit_url = package_edit_url(surface)

    lines = String[]
    if edit_url !== nothing
        push!(lines, "```@meta")
        push!(lines, "EditURL = \"$edit_url\"")
        push!(lines, "```")
        push!(lines, "")
    end
    append!(lines, String[
        "# $name",
        "",
        "``$name`` is listed under `packages:` in an **active** use case.",
        "",
        "## Harness status",
        "",
        "**$(status_label(surface.status))**",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Roles | $(roles == "" ? "—" : roles) |",
        "| Active use cases | $(join(cases, ", ")) |",
        "",
        "See the [Packages overview](../packages.md) and [`packages.toml`](../packages.toml).",
        "",
    ])
    return join(lines, "\n")
end

function render_package_section_table(surfaces::Vector{PackageSurface})
    lines = String[
        "| Name | Roles | Use cases |",
        "|------|-------|-----------|",
    ]
    for surface in surfaces
        roles = join(sort(collect(surface.roles)), ", ")
        roles = roles == "" ? "—" : roles
        case_links = ["[$(r.page_ref)](usecases/$(r.page_ref).md)" for r in surface.cases]
        cases = isempty(case_links) ? "—" : join(case_links, ", ")
        pkg_link = package_doc_href(surface.name, surface.page_path; from_generated=true)
        push!(lines, "| $pkg_link | $roles | $cases |")
    end
    return join(lines, "\n")
end

function render_packages_index(surfaces::Vector{PackageSurface})
    in_harness = filter(s -> s.status === harness, surfaces)
    candidates = filter(s -> s.status === candidate, surfaces)
    contracts = filter(s -> s.status === data, surfaces)

    lines = String[
        "# Packages and data contracts",
        "",
        "Integration surfaces come from **`status: active`** use-case `packages:` frontmatter —",
        "not from draft or deprecated cases, and not only from packages already listed in the",
        "harness [`Project.toml`](https://github.com/railtoolkit/RailToolKit.jl/blob/main/Project.toml).",
        "",
        "Draft cases may list candidate packages; they appear here only after activation.",
        "Package landing pages are generated automatically under `docs/src/generated/packages/`.",
        "",
        "| Status | Meaning |",
        "|--------|---------|",
        "| **In harness** | Julia package is a dependency of RailToolKit |",
        "| **Candidate (external)** | Named by active use cases; not yet a harness `Project.toml` dep |",
        "| **Data contract** | Non-Julia schema / format (`role: data`); never a Pkg dep |",
        "",
        "Inventory (generated from the same frontmatter): [`packages.toml`](packages.toml).",
        "",
    ]

    if isempty(surfaces)
        push!(lines, "_No packages referenced yet — add **active** `UC-*` use cases with `packages:` frontmatter._")
        push!(lines, "")
        return join(lines, "\n")
    end

    if !isempty(in_harness)
        push!(lines, "## In harness")
        push!(lines, "")
        push!(lines, render_package_section_table(in_harness))
        push!(lines, "")
    end
    if !isempty(candidates)
        push!(lines, "## Candidates and external packages")
        push!(lines, "")
        push!(lines, "Referenced by the catalogue but **outside** the current harness dependency set.")
        push!(lines, "")
        push!(lines, render_package_section_table(candidates))
        push!(lines, "")
    end
    if !isempty(contracts)
        push!(lines, "## Data contracts")
        push!(lines, "")
        push!(lines, render_package_section_table(contracts))
        push!(lines, "")
    end
    return join(lines, "\n")
end

function package_sidebar_pages(surfaces::Vector{PackageSurface})
    order = Dict(harness => 1, candidate => 2, data => 3)
    sorted = sort(surfaces; by=s -> (order[s.status], s.name))
    return [s.name => s.page_path for s in sorted if s.page_path !== nothing]
end

function build_package_surfaces!(records::Vector{UseCaseRecord}, src_dir::AbstractString)
    harness_deps = harness_julia_deps()
    pkg_cases, pkg_roles = collect_package_mentions(records)

    generated_pkg_dir = joinpath(src_dir, "generated", "packages")
    mkpath(generated_pkg_dir)

    surfaces = PackageSurface[]
    for name in sort(collect(keys(pkg_cases)))
        roles = get(pkg_roles, name, Set{String}())
        status = classify_package(name, roles, harness_deps)
        page_path = "generated/packages/$name.md"
        surface = PackageSurface(name, roles, pkg_cases[name], status, page_path)
        write(joinpath(src_dir, page_path), render_package_page(surface))
        push!(surfaces, surface)
    end

    sort!(surfaces; by=s -> s.name)
    write_packages_toml!(src_dir, surfaces)
    return surfaces
end
